site_name: Home Server
site_url: http://time0ut07.github.io/HomeServer
theme:
  name: material
  palette:
    scheme: slate
  # logo: img/logo.png
  # favicon: img/logo.png
  features:
    - header.autohide
    - navigation.footer
    # - navigation.expand
    - navigation.path
    - content.code.copy # allows users to copy code blocks

plugins:
  # - offline
  - search
markdown_extensions:
  - pymdownx.highlight: # for colouring code blocks
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true # titles code block with the language
      # linenums: true  # numbers the code block lines
  - pymdownx.inlinehilite # for colouring code blocks
  - pymdownx.snippets # for colouring code blocks
  - pymdownx.superfences # for colouring code blocks
  - attr_list # to add html/css classes with special syntax

nav:
  - Introduction: index.md

  - Getting Started: 
    - getting_started/prerequisites.md
    - getting_started/installation.md
    - getting_started/post_installation.md

  - Set Up:
    - Remote Access: 
      - setup/ra_overview.md
      - setup/ra_method.md
      - setup/ra_tech.md
    - setup/static_ip.md
    - setup/installation.md

  - Portainer: portainer/portainer.md

  - Filebrowser:
    - Overview: filebrowser/filebrowser.md
    - Installation: filebrowser/installation.md